import { BlockType } from '../world/block';
import { CHUNK_SIZE, CHUNK_VOLUME } from '../world/coords';
import {
  INDIRECT_ARGS_WORDS,
  MESH_COUNTER_WORDS,
  MESH_JOB_NEIGHBOR_OFFSET,
  MESH_JOB_WORDS,
  NO_SLOT,
  OPAQUE_QUAD_CAPACITY,
  OPAQUE_VERTEX_CAPACITY,
  PADDED_SIZE,
  PADDED_VOLUME,
  PADDED_WORDS,
  WATER_QUAD_CAPACITY,
  WATER_VERTEX_CAPACITY,
} from '../world/mesh-format';
import { TEXTURE_LAYERS } from './block-textures';
import { GPU_DATA_OFFSET, GPU_PALETTE_OFFSET, GPU_SLOT_WORDS } from '../world/palette-chunk';
import {
  BEACH_MAX_Y,
  CAVE_MAX_Y,
  CAVE_MIN_DENSITY,
  CAVE_MIN_Y,
  DETAIL_AMPLITUDE,
  GRASS_MAX_Y,
  SEA_LEVEL,
  SURFACE_SEARCH,
  TREE_CELL,
  WORLD_MIN_Y,
} from '../world/terrain';

type WgslScalar = 'u32' | 'i32' | 'f32';

/**
 * Constants injected in front of every WGSL module so that buffer layouts, capacities and
 * block ids have a single source of truth in TypeScript.
 */
export const SHADER_CONSTANTS: readonly (readonly [string, number, WgslScalar])[] = [
  ['CHUNK_SIZE', CHUNK_SIZE, 'u32'],
  ['CHUNK_SIZE_I', CHUNK_SIZE, 'i32'],
  ['CHUNK_VOLUME', CHUNK_VOLUME, 'u32'],
  ['SLOT_WORDS', GPU_SLOT_WORDS, 'u32'],
  ['GPU_PALETTE_OFFSET', GPU_PALETTE_OFFSET, 'u32'],
  ['GPU_DATA_OFFSET', GPU_DATA_OFFSET, 'u32'],
  ['PADDED_SIZE', PADDED_SIZE, 'u32'],
  ['PADDED_SIZE_I', PADDED_SIZE, 'i32'],
  ['PADDED_VOLUME', PADDED_VOLUME, 'u32'],
  ['PADDED_WORDS', PADDED_WORDS, 'u32'],
  ['MESH_JOB_WORDS', MESH_JOB_WORDS, 'u32'],
  ['MESH_JOB_NEIGHBOR_OFFSET', MESH_JOB_NEIGHBOR_OFFSET, 'u32'],
  ['NO_SLOT', NO_SLOT, 'u32'],
  ['OPAQUE_QUAD_CAPACITY', OPAQUE_QUAD_CAPACITY, 'u32'],
  ['WATER_QUAD_CAPACITY', WATER_QUAD_CAPACITY, 'u32'],
  ['OPAQUE_VERTEX_CAPACITY', OPAQUE_VERTEX_CAPACITY, 'u32'],
  ['WATER_VERTEX_CAPACITY', WATER_VERTEX_CAPACITY, 'u32'],
  ['INDIRECT_ARGS_WORDS', INDIRECT_ARGS_WORDS, 'u32'],
  ['MESH_COUNTER_WORDS', MESH_COUNTER_WORDS, 'u32'],
  ['BLOCK_AIR', BlockType.Air, 'u32'],
  ['BLOCK_STONE', BlockType.Stone, 'u32'],
  ['BLOCK_DIRT', BlockType.Dirt, 'u32'],
  ['BLOCK_GRASS', BlockType.Grass, 'u32'],
  ['BLOCK_SAND', BlockType.Sand, 'u32'],
  ['BLOCK_WATER', BlockType.Water, 'u32'],
  ['BLOCK_BASALT', BlockType.Basalt, 'u32'],
  ['BLOCK_WOOD', BlockType.Wood, 'u32'],
  ['BLOCK_LEAVES', BlockType.Leaves, 'u32'],
  ['BLOCK_BEDROCK', BlockType.Bedrock, 'u32'],
  ['SEA_LEVEL', SEA_LEVEL, 'i32'],
  ['WORLD_MIN_Y', WORLD_MIN_Y, 'i32'],
  ['BEACH_MAX_Y', BEACH_MAX_Y, 'i32'],
  ['GRASS_MAX_Y', GRASS_MAX_Y, 'i32'],
  ['CAVE_MIN_Y', CAVE_MIN_Y, 'i32'],
  ['CAVE_MAX_Y', CAVE_MAX_Y, 'i32'],
  ['CAVE_MIN_DENSITY', CAVE_MIN_DENSITY, 'f32'],
  ['DETAIL_AMPLITUDE', DETAIL_AMPLITUDE, 'f32'],
  ['SURFACE_SEARCH', SURFACE_SEARCH, 'i32'],
  ['TREE_CELL', TREE_CELL, 'i32'],
  ...TEXTURE_LAYERS.map((name, i) => [`TEX_${name.toUpperCase()}`, i, 'i32'] as const),
];

function literal(value: number, type: WgslScalar): string {
  switch (type) {
    case 'u32':
      if (!Number.isInteger(value) || value < 0 || value > 0xffffffff) throw new RangeError(`bad u32 ${value}`);
      return `${value}u`;
    case 'i32':
      if (!Number.isInteger(value)) throw new RangeError(`bad i32 ${value}`);
      return value < 0 ? `(${value}i)` : `${value}i`;
    case 'f32':
      return Number.isInteger(value) ? `${value}.0` : `${value}`;
  }
}

export function shaderPrelude(): string {
  return [
    '// ---- generated by src/gpu/shader-prelude.ts ----',
    ...SHADER_CONSTANTS.map(([name, value, type]) => `const ${name}: ${type} = ${literal(value, type)};`),
    '',
  ].join('\n');
}

/** Prepends the generated constants to a WGSL module source. */
export function withPrelude(source: string): string {
  return `${shaderPrelude()}\n${source}`;
}
